
/* this is the TPM multicast datagram */

struct TPM_MULTI {
  char magic[24]; /* always has the string TPM_MULTI */
  char mcp_vers[24];
  char plc_vers[24];
  char semaphore[40];
  char fid_vers[24];
  double ctime; /* same as time_t */
  int32_t az_pos;
  int32_t az_actual_pos;
  int32_t az_actual_pos2;
  int32_t az_volts;
  int32_t az_volts2;
  int32_t az_velocity;
  int32_t az_amps;
  int32_t az_amps2;
  int32_t alt_pos;
  int32_t alt_actual_pos;
  int32_t alt_actual_pos2;
  int32_t alt_volts;
  int32_t alt_volts2;
  int32_t alt_amps;
  int32_t alt_amps2;
  int32_t alt_velocity;
  int32_t rot_pos;
  int32_t rot_actual_pos;
  int32_t rot_volts;
  int32_t rot_amps;
  int32_t rot_velocity;
  double az_spt; /* config value, seconds per tick */
  double alt_spt;
  double rot_spt;
  int32_t az_err;
  int32_t alt_err;
  int32_t rot_err;
  float az_plc_volts;
  float az2_plc_volts;
  float alt_plc_volts;
  float alt2_plc_volts;
  float rot_plc_volts;

  float inclinometer;

  uint32_t axis_stat[3];

  int az_fid;
  int alt_fid;
  int rot_fid;
  int32_t az_fid_pos;
  int32_t alt_fid_pos;
  int32_t rot_fid_pos;

  int sp1_door;
  int sp2_door;
  int inst_id[3];

  /* plc analog (in float form) */
  float alt_servo;
  float alt_primary;
  float az_servo;
  float az_primary;
  float az_ff_drive;
  float lift_force;
  float lift_pos;
  float plc_cw[4];

  /* plc words */
  uint16_t plc_words[192];

/* end of MCP data */
/* start of TPM data */
/* all data after plc_words is generated by the
   TPM and not the MCP */

  char tpm_vers[24];
  int az1_stat;
  int az2_stat;
  int alt1_stat;
  int alt2_stat;
  int rot_stat;
  int slip_stat[8];
  float m1_axial_a;
  float m1_axial_b;
  float m1_axial_c;
  float m1_transverse;
  float m1_lateral_e; /* east */
  float m1_lateral_f; /* west */
  int m1_mig_sevr; /* error */
  float m2_axial_a;
  float m2_axial_b;
  float m2_axial_c;
  float m2_y;
  int m2_mig_sevr; /* error */

  /* dewar */
  float dewar_sp1_lb;
  float dewar_sp2_lb;
  float dewar_sp1_psi;
  float dewar_sp2_psi;
  int sevr_sp1; /* error states */
  int sevr_sp2;

  float pmss_pos[4];
  float pmss_pos_error[4];
  float pmss_press[4];
  float pmss_press_error[4];

  float DpTempA; /* these two are from the humidity port */
  float DpTempB;
  float DpDepMean; /* a running avg of DpTempA - DpTempB */
  int   sevr_humid;
  float wind_speed;
  float wind_dir;

  int galil_m1_a[6]; /* actual */
  int galil_m1_c[6]; /* cmd */
  int galil_m1_h[6]; /* homed */
  int galil_m1_sevr; /* error */

  int galil_m2_a[5];
  int galil_m2_c[5];
  int galil_m2_h[5];
  int galil_m2_sevr;

  int galil_m2_piezo_a;
  int galil_m2_piezo_b;
  int galil_m2_piezo_c;
  int galil_m2_piezo_stat;

  float therm0[64]; /* temperature data */
  float therm1[64];
  float therm2[64];
  int tmicro_sevr; /* error on temperature data */
  int cw_limits;
};

/* length of the mcp portion of the TPM_MULTI packet */

#define TPM_MULTI_MCPONLY ((unsigned long)(&(((struct TPM_MULTI *)0)->tpm_vers)))
