on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build_on_macos:
    name: Build macOS wheels
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine build

      - name: Build wheels
        run: |
          pyproject-build -w

      - name: Build source
        if: ${{ matrix.python-version == '3.10' }}
        run: |
          pyproject-build -s

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          twine upload dist/*

  build_on_linux:
    name: Build for Linux and upload to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: tpm-multicast-client ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine build

      - name: Build wheels
        uses: RalfG/python-wheels-manylinux-build@v0.7.0
        with:
          python-versions: 'cp310-cp310 cp311-cp311 cp312-cp312'

      - name: List files
        run: |
          ls -la dist/

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          twine upload dist/*-manylinux*.whl
